### ISSUE TITLE
Using fn$

### ISSUE THREAD

**Issue by doeixd** [lxsmnsyc/thaler#13]
Hello, 

I'm attempting to use thaler with Astro, and I'm encountering some interesting behavior, I'm not sure if I'm using the library correct or not.

When attempting to use fn$ like so:

```
let orders = fn$(get_orders)
```

I get the following error: 
```
Error: fn$ cannot be called during runtime.
    at Module.fn$ (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/thaler/dist/esm/development/index.mjs:47:9)
    at Example (C:\Users\Pglenn\Desktop\amring_web_app\src\components\Example.tsx:24:14)
    at Module.createComponent (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:349:15)
    at __vite_ssr_import_0__.renderToString.renderId.renderId (C:\Users\Pglenn\Desktop\amring_web_app\node_modules\@astrojs\solid-js\dist\server.js:27:14)
    at file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/web/dist/server.js:104:34
    at createRoot (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:58:14)
    at Module.renderToString (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/web/dist/server.js:102:14)
    at Object.renderToStaticMarkup (C:\Users\Pglenn\Desktop\amring_web_app\node_modules\@astrojs\solid-js\dist\server.js:14:16)
    at Object.check (C:\Users\Pglenn\Desktop\amring_web_app\node_modules\@astrojs\solid-js\dist\server.js:7:41)
    at renderFrameworkComponent (C:\Users\Pglenn\Desktop\amring_web_app\node_modules\astro\dist\runtime\server\render\component.js:98:33)
    at async Module.renderComponent (C:\Users\Pglenn\Desktop\amring_web_app\node_modules\astro\dist\runtime\server\render\component.js:346:10)
```

However when I use it like so there is no error: 

```
let orders = fn$(async () => {
  return await get_orders()
})
```

---

Also when I attempt to use fn$ like so: 
```
let resource = afn => {
  let res = fn$(async () => await afn())
  return createAsync(res)
}
```

I get the following error: 

```
Error: Cannot serialize function without reference ID.
    at X.parseFunction (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:8023)
    at X.parse (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:16731)
    at X.parseItems (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:10593)
    at X.parseArray (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:10662)
    at X.parseObject (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:14063)
    at X.parse (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:16643)
    at X.parseProperties (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:10804)
    at X.parsePlainObject (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:11371)
    at X.parseObject (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:14133)
    at X.parse (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:16643)
    at Un (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/seroval/dist/esm/production/index.mjs:3:44834)
    at serializeFunctionBody (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/thaler/dist/esm/development/server.mjs:33:31)
    at fnHandler (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/thaler/dist/esm/development/server.mjs:210:22)
    at subFetch (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/@solidjs/router/dist/data/createAsync.js:47:16)
    at eval (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/@solidjs/router/dist/data/createAsync.js:11:67)
    at load (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:524:78)
    at Module.createResource (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:573:42)
    at Module.createAsync (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/@solidjs/router/dist/data/createAsync.js:11:46)
    at resource (C:/Users/Pglenn/Desktop/amring_web_app/src/components/Example.tsx:20:34)
    at Example (C:/Users/Pglenn/Desktop/amring_web_app/src/components/Example.tsx:22:16)
    at Module.createComponent (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:349:15)
    at __vite_ssr_import_0__.renderToString.renderId.renderId (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/@astrojs/solid-js/dist/server.js:31:36)
    at file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/web/dist/server.js:104:34
    at createRoot (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/dist/server.js:58:14)
    at Module.renderToString (file:///C:/Users/Pglenn/Desktop/amring_web_app/node_modules/solid-js/web/dist/server.js:102:14)
    at Object.renderToStaticMarkup (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/@astrojs/solid-js/dist/server.js:18:38)
    at renderFrameworkComponent (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/astro/dist/runtime/server/render/component.js:209:66)
    at async Module.renderComponent (C:/Users/Pglenn/Desktop/amring_web_app/node_modules/astro/dist/runtime/server/render/component.js:360:10)
```

I assume it's possible to use this function in a primitive way like I've attempted, but it doesn't seem possible. Is this by design? If not this might be a bug.

**Comment by lxsmnsyc** [comment]
1. Yes thaler doesn't support this kind of pattern
2. fn$ doesn't support higher-order functions, as functions are not serializable and prone to security concerns.

**Comment by doeixd** [comment]
Thank you for the additional information.
